### PR TITLE
Add pingback URL functionality

### PR DESCRIPTION
**Pull request by daineX**
Pivotal: part of https://www.pivotaltracker.com/story/show/38734291

Add option to ping a URL after a successful run to see if the robot is still alive

### CODE REVIEW

**Comment by deets** [comment]
Why was the configurability removed? A hard-coded default is ok, but a way to locally override it with e.g. Nothing when testing might be nice. I found myself in that very position with the latest addition, the raise-exceptions-rework.

**Comment by daineX** [comment]
You are right; in the end it might the same amount of work to add the parameter in all affected classes as adding it to each configuration file.

**Comment by deets** [comment]
Another immediate idea is of course that eventually we probably want to extend this to a full fledged reporting - e.g. duration of (sub)tasks, errors, etc. I'm not suggesting to introduce that right now, but as we are working on this atm in the infrastructure team, we might as well try & incorporate something there soonish.

**Comment by daineX** [comment]
The only reason why I'm adding this is that we finally want to use abl.robot (and thereby get rid of abl.devtools). The base class in abl.devtools already had this functionality so it has to be re-added for our monitoring system to work.

**Comment by deets** [comment]
good enough for me & for now, just make it configurable (I'm also happy with just overriding via commandline, for now we don't need a full section in the config I guess). Then I'll merge.

**Comment by daineX** [comment]
It is configurable now by specifying it in the config. Please merge :)

**Pull request merged**
