### PR TITLE
F use os tempdir

### PR DESCRIPTION
**Pull request by ghost**
- fixes the default log file directory used by robot.
- fixes requirement to set up venv
- fixes email notification test

### CODE REVIEW

**Comment by deets** [comment]
@daineX @sixohsix Nicolas found this little problem on windows. I'm not 100% sure about the relaxed abl.util-requirement. I uploaded 0.1.12 to PyPI, but are you okay with >= reqs, or would you prefer exact dependency-pinning? Is there a report generated somehow?

**Comment by sixohsix** [comment]
The reason we use specific versions in requirements.txt is that using >= produces non-deterministic deployments. For instance, you could do a whole test run with abl.util 1.1.11 that passes, then deploys to production with 1.1.12 and fails.

However, the requirements.txt file is only used per project so the fact that you have >= here doesn't break ableton.com or backend.

You can use `pip freeze > requirements.txt` to dump all current versions in your virtualenv into a new requirements file with current versions.

So, yeah, specific versions are preferred in requirements.txt. Is that cool with you?

**Comment by sixohsix** [comment]
The actual code change here is fully fine by me. Feel free to merge.

**Comment by ghost** [comment]
I think we should drop that part of my branch, as it's not really related. I don't know how you handle the transitive dependencies across projects, this seems like a whole can of worms too.

**Comment by Pankrat** [comment]
If I may chime in here: Libraries should use `>=` while applications should use `==`. Exact pinning of dependencies in a library gets painful if you have to use a newer version of a required library in a downstream application.

**Comment by deets** [comment]
If I may chime in here: Libraries should use >= while applications should use ==. Exact pinning of dependencies in a library gets painful if you have to use a newer version of a required library in a downstream application.

Good point, kind of pins down my unease with exact requirements that I wanted to express in an answer to mike.

So I will just go forward & merge Nicolas' pull request.

Thanks!

Diez

**Pull request merged**
